<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'ORÇAMENTO - Para Você envio',
	'heading' => 'Envio de novo formulário',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Marcado',
		'checkbox_unchecked' => 'Desmarcado',
		'submitted_from' => 'Formulário enviado do site: %s',
		'submitted_by' => 'Endereço IP do visitante: %s',
		'too_many_submissions' => 'Muitos envios recentes deste IP',
		'failed_to_send_email' => 'Falha no envio do email',
		'invalid_reCAPTCHA_private_key' => 'Chave privada do reCAPTCHA inválida.',
		'invalid_reCAPTCHA2_private_key' => 'Chave privada do reCAPTCHA 2.0 inválida.',
		'invalid_reCAPTCHA2_server_response' => 'Resposta do servidor reCAPTCHA 2.0 inválida.',
		'invalid_field_type' => 'Tipo de campo desconhecido \"%s\".',
		'invalid_form_config' => 'O campo \"%s\" possui uma configuração inválida.',
		'unknown_method' => 'Método de solicitação de servidor desconhecido'
	),
	'email' => array(
		'from' => 'atendimento@espacovitoriane.com.br',
		'to' => 'atendimento@espacovitoriane.com.br'
	),
	'fields' => array(
		'Email' => array(
			'order' => 4,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Email\" é obrigatório.',
				'format' => 'O campo \"Email\" possui um email inválido.'
			)
		),
		'custom_U3805' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Nome Completo',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Nome Completo\" é obrigatório.'
			)
		),
		'custom_U3821' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Telefone',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Telefone\" é obrigatório.'
			)
		),
		'custom_U3837' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Data desejada para o evento',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Data desejada para o evento\" é obrigatório.'
			)
		),
		'custom_U3853' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Número de convidados',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Número de convidados\" é obrigatório.'
			)
		),
		'custom_U3966' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Deseja dar algum detalhe a mais?',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U3673' => array(
			'order' => 2,
			'type' => 'checkboxgroup',
			'label' => 'Qual o local da cerimônia?',
			'required' => true,
			'optionItems' => array(
				'Igreja',
				'No Local',
				'Não definido',
				'Não haverá cerimônia'
			),
			'errors' => array(
				'required' => 'O campo \"Qual o local da cerimônia?\" é obrigatório.',
				'format' => 'O campo \"Qual o local da cerimônia?\" possui um valor inválido.'
			)
		),
		'custom_U3504' => array(
			'order' => 1,
			'type' => 'checkboxgroup',
			'label' => 'Qual o perfil do seu evento?',
			'required' => true,
			'optionItems' => array(
				'Casamento',
				'Bodas',
				'Festa de Debutante',
				'Aniversário',
				'Bar Mitzvah',
				'Noivado',
				'Batizado',
				'Outro'
			),
			'errors' => array(
				'required' => 'O campo \"Qual o perfil do seu evento?\" é obrigatório.',
				'format' => 'O campo \"Qual o perfil do seu evento?\" possui um valor inválido.'
			)
		)
	)
);

process_form($form);
?>
